services:
  mysql:
    image: mysql:8.0
    container_name: argus-mysql
    restart: unless-stopped
    env_file: [../.env]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT_HOST}:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - server_b_logic_mysql-data:/var/lib/mysql
    networks: [argus-shared-net]

  nginx:
      image: nginx:1.25-alpine
      container_name: argus-nginx
      restart: unless-stopped
      ports:
        - "${WEB_PORT:-8081}:80"
      volumes:
        - ./frontend:/usr/share/nginx/html
        # MUDANÇA AQUI: Montamos na pasta de templates para o Nginx processar corretamente
        - ./nginx/conf/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      environment:
        - BACKEND_PORT=3000
        - SERVER_A_IP=argus-backend
      networks:
        - argus-shared-net

networks:
  argus-shared-net:
    external: true
    name: argus-shared-net

volumes:
  server_b_logic_mysql-data: