server {
    listen 80;
    server_name localhost;

    # Proxy para a API
    location /api/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- INÍCIO DA MUDANÇA ---
    # Novo proxy para a conexão MQTT WebSocket
    location /mqtt {
        proxy_pass http://emqx:8083; # Repassa para o broker na porta interna
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
    # --- FIM DA MUDANÇA ---

    # Servir o frontend (sem mudanças)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}