services:
  emqx:
    image: emqx/emqx:5.1.0
    container_name: argus-broker
    hostname: emqx
    restart: unless-stopped
    environment:
      - "EMQX_ALLOW_ANONYMOUS=true"
      - "EMQX_DASHBOARD__DEFAULT_PASSWORD=${MQTT_PASSWORD}"
    ports:
      - "${MQTT_PORT_TCP:-1883}:1883"
      - "${MQTT_PORT_DASHBOARD:-18083}:18083"

  backend:
    build: .
    container_name: argus-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    env_file: [../.env]
    environment:
      - DB_HOST=${SERVER_B_IP}
      - DB_PORT=${DB_PORT:-3306} 
      - DB_USER=${DB_BACKEND_USER}
      - DB_PASSWORD=${DB_BACKEND_USER_PASSWORD}
      - DB_NAME=${DB_DATABASE}
      - MQTT_URL=mqtt://emqx:1883
      - MQTT_USER=${MQTT_USERNAME}
      - MQTT_PASS=${MQTT_PASSWORD}